/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'discountText' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Category = IDL.Variant({
  'jewellery' : IDL.Null,
  'offer' : IDL.Null,
  'accessories' : IDL.Null,
  'ladies' : IDL.Null,
  'daily' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : Category,
  'badge' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StoreDTO = IDL.Record({
  'whatsapp' : IDL.Text,
  'offers' : IDL.Vec(Offer),
  'announcement' : IDL.Text,
  'activeProducts' : IDL.Vec(Product),
});
export const StoreConfig = IDL.Record({
  'whatsapp' : IDL.Text,
  'announcement' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOffer' : IDL.Func([Offer], [IDL.Nat], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteOffer' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getStore' : IDL.Func([], [StoreDTO], ['query']),
  'getStoreConfig' : IDL.Func([], [StoreConfig], ['query']),
  'getStorePublicContent' : IDL.Func([], [StoreDTO], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOffer' : IDL.Func([Offer], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateStoreConfig' : IDL.Func([StoreConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'discountText' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Category = IDL.Variant({
    'jewellery' : IDL.Null,
    'offer' : IDL.Null,
    'accessories' : IDL.Null,
    'ladies' : IDL.Null,
    'daily' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : Category,
    'badge' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StoreDTO = IDL.Record({
    'whatsapp' : IDL.Text,
    'offers' : IDL.Vec(Offer),
    'announcement' : IDL.Text,
    'activeProducts' : IDL.Vec(Product),
  });
  const StoreConfig = IDL.Record({
    'whatsapp' : IDL.Text,
    'announcement' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOffer' : IDL.Func([Offer], [IDL.Nat], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteOffer' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStore' : IDL.Func([], [StoreDTO], ['query']),
    'getStoreConfig' : IDL.Func([], [StoreConfig], ['query']),
    'getStorePublicContent' : IDL.Func([], [StoreDTO], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOffer' : IDL.Func([Offer], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateStoreConfig' : IDL.Func([StoreConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };